import = [
    #"~/.config/alacritty/themes/tokyo-night-storm.toml"
    "~/.config/alacritty/themes/tokyo-night.toml"
]

[font]
size = 8

[font.bold]
family = "JetBrainsMono"
style = "Medium"

[font.bold_italic]
family = "JetBrainsMono"
style = "Medium Italic"

[font.italic]
family = "JetBrainsMono"
style = "ExtraLight Italic"

[font.normal]
family = "JetBrainsMono"
style = "ExtraLight"
