[colors.bright]
black = "#2f334d"
blue = "#3e68d7"
cyan = "#86e1fc"
green = "#4fd6be"
magenta = "#c099ff"
red = "#c53b53"
white = "#c0caf5"
yellow = "#ffc777"

[colors.normal]
black = "#222436"
blue = "#82aaff"
cyan = "#86e1fc"
green = "#c3e88d"
magenta = "#ff007c"
red = "#ff757f"
white = "#c0caf5"
yellow = "#ffc777"

[colors.primary]
background = "#222436"
foreground = "#c8d3f5"
